package main

import (
	"fmt"
	"os"
)

// printRobotHelp outputs the comprehensive robot help text and exits.
func printRobotHelp() {
	fmt.Println("bt (Beads TUI) AI Agent Interface")
	fmt.Println("====================================")
	fmt.Println("This tool provides structural analysis of the issue tracker graph (DAG).")
	fmt.Println("Use these commands to understand project state without parsing raw JSONL.")
	fmt.Println("")
	fmt.Println("Output format:")
	fmt.Println("  --format json|toon")
	fmt.Println("      Structured output encoding for --robot-* commands (default: json).")
	fmt.Println("      Env: BT_OUTPUT_FORMAT, TOON_DEFAULT_FORMAT.")
	fmt.Println("  --stats")
	fmt.Println("      Print JSON vs TOON token estimates to stderr (or set TOON_STATS=1).")
	fmt.Println("")
	fmt.Println("Commands:")
	fmt.Println("  --robot-plan")
	fmt.Println("      Outputs a dependency-respecting execution plan as JSON.")
	fmt.Println("      Shows what can be worked on now and what it unblocks.")
	fmt.Println("      Key fields:")
	fmt.Println("      - tracks: Independent work streams that can be parallelized")
	fmt.Println("      - items: Actionable issues sorted by priority within each track")
	fmt.Println("      - unblocks: Issues that become actionable when this item is done")
	fmt.Println("      - summary: Highlights highest-impact item to work on first")
	fmt.Println("")
	fmt.Println("  --robot-insights")
	fmt.Println("      Outputs a JSON object containing deep graph analysis.")
	fmt.Println("      Key metrics explained:")
	fmt.Println("      - PageRank: Measures 'blocking power'. High score = Fundamental dependency.")
	fmt.Println("      - Betweenness: Measures 'bottleneck status'. High score = Connects disparate clusters.")
	fmt.Println("      - CriticalPathScore: Heuristic for depth. High score = Blocking a long chain of work.")
	fmt.Println("      - Hubs/Authorities: HITS algorithm scores for dependency relationships.")
	fmt.Println("      - Cycles: Lists of circular dependencies (unhealthy state).")
	fmt.Println("")
	fmt.Println("  --robot-priority")
	fmt.Println("      Outputs priority recommendations as JSON.")
	fmt.Println("      Compares impact scores to current priorities and suggests adjustments.")
	fmt.Println("      Key fields:")
	fmt.Println("      - recommendations: Sorted by confidence, then impact score")
	fmt.Println("      - confidence: 0-1 score indicating strength of recommendation")
	fmt.Println("      - reasoning: Human-readable explanations for the suggestion")
	fmt.Println("      - direction: 'increase' or 'decrease' priority")
	fmt.Println("")
	fmt.Println("  --robot-triage")
	fmt.Println("      THE MEGA-COMMAND: Unified triage output combining all analysis.")
	fmt.Println("      Single entry point for AI agents - one call gets everything needed.")
	fmt.Println("      Key sections:")
	fmt.Println("      - meta: Generation timestamp, data stats")
	fmt.Println("      - quick_ref: At-a-glance summary (open/actionable/blocked counts, top 3 picks)")
	fmt.Println("      - recommendations: Ranked actionable items with scores and reasoning")
	fmt.Println("      - quick_wins: Low-complexity, high-impact items")
	fmt.Println("      - blockers_to_clear: Items that unblock the most downstream work")
	fmt.Println("      - project_health: Counts, graph metrics, overall status")
	fmt.Println("      - commands: Copy-paste commands for common next steps")
	fmt.Println("")
	fmt.Println("  --robot-next")
	fmt.Println("      Minimal triage: returns only the single top recommendation.")
	fmt.Println("      Output includes: id, title, score, reasons, claim_command, show_command")
	fmt.Println("      Use when you just need to know \"what should I work on next?\"")
	fmt.Println("")
	fmt.Println("  --search \"query\" [--robot-search]")
	fmt.Println("      Semantic vector search over issue titles/descriptions.")
	fmt.Println("      Builds/updates a local on-disk vector index on first run.")
	fmt.Println("      Use --robot-search to emit JSON for automation.")
	fmt.Println("      Optional hybrid re-ranking:")
	fmt.Println("      - --search-mode=text|hybrid (default: BT_SEARCH_MODE or text)")
	fmt.Println("      - --search-preset=default|bug-hunting|sprint-planning|impact-first|text-only")
	fmt.Println("      - --search-weights='{\"text\":0.4,\"pagerank\":0.2,\"status\":0.15,\"impact\":0.1,\"priority\":0.1,\"recency\":0.05}'")
	fmt.Println("")
	fmt.Println("  --emit-script [--script-limit=N]")
	fmt.Println("      Emits a shell script for top-N recommendations (default: 5).")
	fmt.Println("      Includes hash/config header for deterministic ordering.")
	fmt.Println("      Output: br show commands for each item, commented claim commands")
	fmt.Println("      Options: --script-format=bash|fish|zsh, --script-limit=N")
	fmt.Println("      Example: bt --emit-script > work.sh && bash work.sh")
	fmt.Println("      Example: bt --emit-script --script-limit=3")
	fmt.Println("")
	fmt.Println("  --robot-history")
	fmt.Println("      Outputs bead-to-commit correlations as JSON.")
	fmt.Println("      Tracks which code changes relate to which beads via git history analysis.")
	fmt.Println("      Key sections:")
	fmt.Println("      - stats: Summary (total beads, beads with commits, avg cycle time)")
	fmt.Println("      - histories: Per-bead data (events, commits, milestones, cycle_time)")
	fmt.Println("      - commit_index: Reverse lookup from commit SHA to bead IDs")
	fmt.Println("      Flags:")
	fmt.Println("      - --bead-history <id>: Filter to single bead")
	fmt.Println("      - --history-since <ref>: Limit to recent commits")
	fmt.Println("      - --history-limit <n>: Max commits to analyze (default: 500)")
	fmt.Println("      - --min-confidence <0.0-1.0>: Filter by minimum confidence score")
	fmt.Println("      Example: bt --robot-history --history-since '30 days ago'")
	fmt.Println("      Example: bt --robot-history --min-confidence 0.7")
	fmt.Println("")
	fmt.Println("  --robot-file-beads <path>")
	fmt.Println("      Outputs beads that have touched a file path as JSON.")
	fmt.Println("      Answers: 'What beads have touched this file, and why?'")
	fmt.Println("      Key sections:")
	fmt.Println("      - file_path: The queried file path")
	fmt.Println("      - open_beads: Currently open beads that touched this file")
	fmt.Println("      - closed_beads: Recently closed beads (limited by --file-beads-limit)")
	fmt.Println("      - total_beads: Total count of beads")
	fmt.Println("      Each bead includes: bead_id, title, status, commit_shas, last_touch, total_changes")
	fmt.Println("      Flags:")
	fmt.Println("      - --file-beads-limit <n>: Max closed beads to show (default: 20)")
	fmt.Println("      Example: bt --robot-file-beads pkg/auth/token.go")
	fmt.Println("      Example: bt --robot-file-beads pkg/auth")
	fmt.Println("")
	fmt.Println("  --robot-file-hotspots")
	fmt.Println("      Outputs files touched by the most beads as JSON.")
	fmt.Println("      Identifies potential conflict zones or high-churn areas.")
	fmt.Println("      Key sections:")
	fmt.Println("      - hotspots: Array of {file_path, total_beads, open_beads, closed_beads}")
	fmt.Println("      - stats: Index statistics (total_files, total_bead_links)")
	fmt.Println("      Flags:")
	fmt.Println("      - --hotspots-limit <n>: Max hotspots to show (default: 10)")
	fmt.Println("      Example: bt --robot-file-hotspots")
	fmt.Println("")
	fmt.Println("  --robot-impact <files>")
	fmt.Println("      Analyzes impact of modifying files - what beads might be affected?")
	fmt.Println("      Critical for agents: check before making changes to avoid conflicts.")
	fmt.Println("      Key sections:")
	fmt.Println("      - risk_level: low/medium/high/critical based on open beads")
	fmt.Println("      - affected_beads: Beads touching these files with relevance scores")
	fmt.Println("      - warnings: Actionable warnings about potential conflicts")
	fmt.Println("      - summary: Human-readable impact summary")
	fmt.Println("      Input: Comma-separated file paths")
	fmt.Println("      Example: bt --robot-impact pkg/auth/token.go")
	fmt.Println("      Example: bt --robot-impact pkg/auth/token.go,pkg/auth/session.go")
	fmt.Println("")
	fmt.Println("  --robot-file-relations <path>")
	fmt.Println("      Outputs files that frequently co-change with the given file.")
	fmt.Println("      Reveals hidden coupling: what other files typically change together?")
	fmt.Println("      Key fields:")
	fmt.Println("      - total_commits: How many commits touched this file")
	fmt.Println("      - related_files: Files that co-change, with correlation scores")
	fmt.Println("        - correlation: 0.0-1.0 (e.g., 0.8 = changed together in 80% of commits)")
	fmt.Println("        - sample_commits: Example commit SHAs showing co-change")
	fmt.Println("      Options:")
	fmt.Println("      - --relations-threshold <0.0-1.0>: Min correlation (default 0.5)")
	fmt.Println("      - --relations-limit <n>: Max related files to return (default 10)")
	fmt.Println("      Example: bt --robot-file-relations pkg/auth/token.go")
	fmt.Println("      Example: bt --robot-file-relations pkg/auth/token.go --relations-threshold 0.3")
	fmt.Println("")
	fmt.Println("  --robot-related <bead-id>")
	fmt.Println("      Outputs beads related to a specific bead as JSON.")
	fmt.Println("      Discovers related work across multiple dimensions:")
	fmt.Println("      - file_overlap: Beads touching the same files")
	fmt.Println("      - commit_overlap: Beads sharing commits")
	fmt.Println("      - dependency_cluster: Beads in the same dependency graph area")
	fmt.Println("      - concurrent: Beads active in overlapping time windows")
	fmt.Println("      Key fields per related bead:")
	fmt.Println("      - relevance: 0-100 score indicating strength of relationship")
	fmt.Println("      - reason: Human-readable explanation of the connection")
	fmt.Println("      - shared_files/shared_commits: Evidence of overlap")
	fmt.Println("      Options:")
	fmt.Println("      - --related-min-relevance <0-100>: Min relevance score (default 20)")
	fmt.Println("      - --related-max-results <n>: Max results per category (default 10)")
	fmt.Println("      - --related-include-closed: Include closed beads")
	fmt.Println("      Example: bt --robot-related bv-abc1")
	fmt.Println("      Example: bt --robot-related bv-abc1 --related-include-closed")
	fmt.Println("")
	fmt.Println("  --robot-sprint-list")
	fmt.Println("      Outputs all sprints as JSON for planning and forecasting.")
	fmt.Println("      Key fields:")
	fmt.Println("      - generated_at: Timestamp of the output")
	fmt.Println("      - sprint_count: Number of sprints")
	fmt.Println("      - sprints: Array of sprint objects (id, name, start_date, end_date, bead_ids)")
	fmt.Println("      Example: bt --robot-sprint-list")
	fmt.Println("")
	fmt.Println("  --robot-sprint-show <id>")
	fmt.Println("      Outputs details for a specific sprint as JSON.")
	fmt.Println("      Returns the full sprint object with all fields.")
	fmt.Println("      Example: bt --robot-sprint-show sprint-1")
	fmt.Println("")
	fmt.Println("  --robot-burndown <id|current>")
	fmt.Println("      Outputs burndown data for a sprint as JSON.")
	fmt.Println("      Use 'current' to get the active sprint, or specify sprint ID.")
	fmt.Println("      Key fields:")
	fmt.Println("      - total_days, elapsed_days, remaining_days")
	fmt.Println("      - total_issues, completed_issues, remaining_issues")
	fmt.Println("      - ideal_burn_rate, actual_burn_rate")
	fmt.Println("      - projected_complete: Estimated completion date")
	fmt.Println("      - on_track: Whether sprint will complete on time")
	fmt.Println("      - daily_points: Actual burndown data points")
	fmt.Println("      - ideal_line: Expected burndown line")
	fmt.Println("      Example: bt --robot-burndown current")
	fmt.Println("      Example: bt --robot-burndown sprint-1")
	fmt.Println("")
	fmt.Println("  --robot-forecast <id|all>")
	fmt.Println("      Outputs ETA forecast for a specific bead or all open issues.")
	fmt.Println("      Returns estimated completion date, confidence, and factors.")
	fmt.Println("      Options:")
	fmt.Println("        --forecast-label=X    Filter by label")
	fmt.Println("        --forecast-sprint=Y   Filter by sprint")
	fmt.Println("        --forecast-agents=N   Parallel agents (default: 1)")
	fmt.Println("      Example: bt --robot-forecast bv-123")
	fmt.Println("      Example: bt --robot-forecast all --forecast-label=backend")
	fmt.Println("      Example: bt --robot-forecast all --forecast-agents=2")
	fmt.Println("")
	fmt.Println("  --robot-capacity [--agents=N] [--capacity-label=X]")
	fmt.Println("      Outputs capacity simulation and completion projection as JSON.")
	fmt.Println("      Analyzes work remaining, parallelizability, and bottlenecks.")
	fmt.Println("      Key fields:")
	fmt.Println("        - total_minutes: Sum of estimated work across open issues")
	fmt.Println("        - parallelizable_pct: Percentage that can be parallelized")
	fmt.Println("        - serial_minutes: Work that must be done sequentially")
	fmt.Println("        - estimated_days: Projected completion time with N agents")
	fmt.Println("        - bottlenecks: Issues limiting parallelization")
	fmt.Println("      Options:")
	fmt.Println("        --agents=N           Number of parallel agents (default: 1)")
	fmt.Println("        --capacity-label=X   Filter analysis to label's subgraph")
	fmt.Println("      Example: bt --robot-capacity --agents=3")
	fmt.Println("      Example: bt --robot-capacity --capacity-label=backend")
	fmt.Println("")
	fmt.Println("  --emit-script [--script-limit=N] [--script-format=bash|fish|zsh]")
	fmt.Println("      Emits a shell script for top-N priority recommendations.")
	fmt.Println("      Useful for agent workflows and automation.")
	fmt.Println("      Output includes:")
	fmt.Println("        - Header comment with data hash and generation time")
	fmt.Println("        - br show commands for each recommended item")
	fmt.Println("        - Commented br update commands to claim items")
	fmt.Println("      Options:")
	fmt.Println("        --script-limit=N      Number of items (default: 5)")
	fmt.Println("        --script-format=X     Script format: bash, fish, zsh")
	fmt.Println("      Example: bt --emit-script")
	fmt.Println("      Example: bt --emit-script --script-limit=3")
	fmt.Println("      Example: bt --emit-script --script-format=fish > work.fish")
	fmt.Println("      Example: bt --emit-script | bash  # Show top 5 items")
	fmt.Println("")
	fmt.Println("  --export-md <file>")
	fmt.Println("      Generates a readable status report with Mermaid.js visualizations.")
	fmt.Println("      Runs pre-export and post-export hooks if configured in .bt/hooks.yaml")
	fmt.Println("")
	fmt.Println("  --no-hooks")
	fmt.Println("      Skip running hooks during export. Useful for CI or quick exports.")
	fmt.Println("")
	fmt.Println("  Hook Configuration (.bt/hooks.yaml)")
	fmt.Println("      Configure hooks to automate export workflows:")
	fmt.Println("      - pre-export: Validation, notifications (failure cancels export)")
	fmt.Println("      - post-export: Notifications, uploads (failure logged only)")
	fmt.Println("      Environment variables: BT_EXPORT_PATH, BT_EXPORT_FORMAT,")
	fmt.Println("        BT_ISSUE_COUNT, BT_TIMESTAMP")
	fmt.Println("")
	fmt.Println("  --diff-since <commit|date>")
	fmt.Println("      Shows changes since a historical point.")
	fmt.Println("      Accepts: SHA, branch name, tag, HEAD~N, or date (YYYY-MM-DD)")
	fmt.Println("      Key output:")
	fmt.Println("      - new_issues: Issues added since then")
	fmt.Println("      - closed_issues: Issues that were closed")
	fmt.Println("      - removed_issues: Issues deleted from tracker")
	fmt.Println("      - modified_issues: Issues with field changes")
	fmt.Println("      - new_cycles: Circular dependencies introduced")
	fmt.Println("      - resolved_cycles: Circular dependencies fixed")
	fmt.Println("      - summary.health_trend: 'improving', 'degrading', or 'stable'")
	fmt.Println("")
	fmt.Println("  --as-of <commit|date>")
	fmt.Println("      View issue state at a point in time (works with all robot commands).")
	fmt.Println("      Useful for historical analysis without modifying the working tree.")
	fmt.Println("      Robot outputs include 'as_of' and 'as_of_commit' metadata fields.")
	fmt.Println("      Examples: --as-of HEAD~30, --as-of v1.0.0, --as-of '2024-01-01'")
	fmt.Println("")
	fmt.Println("  --robot-diff")
	fmt.Println("      Output diff as JSON (use with --diff-since).")
	fmt.Println("      Fields: generated_at, resolved_revision, from_data_hash, to_data_hash, diff{...}")
	fmt.Println("      Diff payload includes metric deltas, cycles introduced/resolved, and modified issues.")
	fmt.Println("")
	fmt.Println("  --robot-recipes")
	fmt.Println("      Lists all available recipes as JSON.")
	fmt.Println("      Output: {recipes: [{name, description, source}]}")
	fmt.Println("      Sources: 'builtin', 'user' (~/.config/bv/recipes.yaml), 'project' (.bt/recipes.yaml)")
	fmt.Println("")
	fmt.Println("  --robot-schema [--schema-command=NAME]")
	fmt.Println("      Outputs JSON Schema definitions for all robot command outputs.")
	fmt.Println("      Useful for validation, tool integration, and understanding output structure.")
	fmt.Println("      Key fields:")
	fmt.Println("        - schema_version: Version of the schema format")
	fmt.Println("        - envelope: Common fields present in all robot outputs")
	fmt.Println("        - commands: Map of command name -> JSON Schema definition")
	fmt.Println("      Options:")
	fmt.Println("        --schema-command=NAME: Output schema for specific command only")
	fmt.Println("      Example: bt --robot-schema")
	fmt.Println("      Example: bt --robot-schema --schema-command=robot-triage")
	fmt.Println("")
	fmt.Println("  --robot-label-health")
	fmt.Println("      Outputs label health metrics as JSON (velocity, freshness, flow, criticality).")
	fmt.Println("      Includes label summaries, detailed metrics, and cross-label dependencies.")
	fmt.Println("      Key fields: health_level (healthy|warning|critical), velocity_score, flow_score.")
	fmt.Println("")
	fmt.Println("  --robot-label-flow")
	fmt.Println("      Outputs cross-label dependency flow as JSON (label->label edges).")
	fmt.Println("      Key fields: labels[], flow_matrix[from][to], dependencies[{from,to,count,issue_ids}],")
	fmt.Println("                  bottleneck_labels (highest outgoing), total_cross_label_deps.")
	fmt.Println("      Use when you need to see which labels are blocking others at a glance.")
	fmt.Println("")
	fmt.Println("  --robot-label-attention [--attention-limit=N]")
	fmt.Println("      Outputs attention-ranked labels as JSON (default limit: 5).")
	fmt.Println("      Labels ranked by attention score = (pagerank * staleness * block_impact) / velocity.")
	fmt.Println("      Key fields: rank, label, attention_score, normalized_score, reason, blocked_count, stale_count.")
	fmt.Println("      Use to identify which labels need the most focus based on centrality and health factors.")
	fmt.Println("")
	fmt.Println("  --robot-alerts")
	fmt.Println("      Outputs drift + proactive alerts as JSON (staleness, cascades, density, cycles).")
	fmt.Println("      Filters: --severity=<info|warning|critical>, --alert-type=<type>, --alert-label=<label>")
	fmt.Println("      Fields: type, severity, message, issue_id, label, detected_at, details[].")
	fmt.Println("")
	fmt.Println("  --robot-graph [--graph-format=json|dot|mermaid] [--graph-root=ID] [--graph-depth=N]")
	fmt.Println("      Outputs dependency graph in specified format (default: JSON adjacency).")
	fmt.Println("      Formats:")
	fmt.Println("        - json: Adjacency list with nodes[], edges[], metadata")
	fmt.Println("        - dot: Graphviz DOT format (render with: dot -Tpng file.dot -o graph.png)")
	fmt.Println("        - mermaid: Mermaid diagram format (paste into GitHub/markdown)")
	fmt.Println("      Options:")
	fmt.Println("        --label LABEL: Filter to issues with specific label")
	fmt.Println("        --graph-root ID: Extract subgraph starting from root issue")
	fmt.Println("        --graph-depth N: Limit subgraph depth (0 = unlimited)")
	fmt.Println("      Fields: format, graph (string for dot/mermaid), nodes, edges, filters_applied, explanation")
	fmt.Println("      Example: bt --robot-graph --graph-format=dot --label=api > api-deps.dot")
	fmt.Println("")
	fmt.Println("  --export-graph <path.png|path.svg> [--graph-style=force|grid] [--graph-preset=compact|roomy]")
	fmt.Println("      Export dependency graph as PNG or SVG image (pure Go, no external dependencies).")
	fmt.Println("      Format is inferred from file extension (.png or .svg).")
	fmt.Println("")
	fmt.Println("      Styles:")
	fmt.Println("        --graph-style=force (default): Beautiful force-directed layout")
	fmt.Println("          - Physics-based positioning (Fruchterman-Reingold algorithm)")
	fmt.Println("          - Dark Dracula-inspired theme with vibrant status colors")
	fmt.Println("          - Curved bezier edges with glow effects")
	fmt.Println("          - Node size reflects importance (PageRank + betweenness)")
	fmt.Println("          - Priority badges, drop shadows, gradients")
	fmt.Println("")
	fmt.Println("        --graph-style=grid: Simple hierarchical grid layout")
	fmt.Println("          - Nodes arranged by critical path depth")
	fmt.Println("          - Light theme with pastel colors")
	fmt.Println("")
	fmt.Println("      Options:")
	fmt.Println("        --label LABEL: Filter to issues with specific label")
	fmt.Println("        --graph-preset: Layout spacing - 'compact' (default) or 'roomy'")
	fmt.Println("        --graph-title: Custom title for the graph header")
	fmt.Println("")
	fmt.Println("      Example: bt --export-graph deps.svg --label=api --graph-title='API Dependencies'")
	fmt.Println("      Example: bt --export-graph full.png --graph-style=force --graph-preset=roomy")
	fmt.Println("")
	fmt.Println("  --robot-insights")
	fmt.Println("      Graph metrics JSON for agents.")
	fmt.Println("      Top lists: Bottlenecks (betweenness), Keystones (critical path), Influencers (eigenvector),")
	fmt.Println("                 Cores (k-core), Articulation points (cut vertices), Slack (parallelism headroom).")
	fmt.Println("      Full maps (capped by BT_INSIGHTS_MAP_LIMIT): pagerank, betweenness, eigenvector, hubs/authorities, core_number, slack.")
	fmt.Println("      status captures per-metric state: computed|approx|timeout|skipped with elapsed_ms and reasons.")
	fmt.Println("      Shared fields: data_hash, analysis_config.")
	fmt.Println("      Quick jq: jq '.full_stats.core_number | to_entries | sort_by(-.value)[:5]'   # top k-core nodes")
	fmt.Println("                 jq '.Articulation'                                                  # structural cut points")
	fmt.Println("                 jq '.Slack[:5]'                                                     # highest slack (parallel-friendly)")
	fmt.Println("      advanced_insights: Canonical structure for advanced graph features:")
	fmt.Println("        - topk_set: Best k issues for maximum downstream unlock (status: pending)")
	fmt.Println("        - coverage_set: Minimal set covering all critical paths (status: pending)")
	fmt.Println("        - k_paths: K-shortest critical paths through the graph (status: pending)")
	fmt.Println("        - parallel_cut: Suggestions for maximizing parallel work (status: pending)")
	fmt.Println("        - parallel_gain: Parallelization metrics for recommendations (status: pending)")
	fmt.Println("        - cycle_break: Suggestions for breaking cycles with minimal impact (status: available)")
	fmt.Println("        Per-feature: status (available|pending|skipped|error), items, usage hints")
	fmt.Println("        Config: caps for deterministic output (topk<=5, paths<=5, path_len<=50, etc.)")
	fmt.Println("        Quick jq: jq '.advanced_insights.cycle_break'   # cycle break suggestions")
	fmt.Println("")
	fmt.Println("  --robot-plan")
	fmt.Println("      Execution tracks grouped for parallel work. Includes data_hash, analysis_config, status.")
	fmt.Println("      plan.tracks[].items[].unblocks shows what completes next; summary.highest_impact surfaces best unblocker.")
	fmt.Println("")
	fmt.Println("  --robot-priority")
	fmt.Println("      Priority recommendations with explanations. Includes data_hash, analysis_config, status.")
	fmt.Println("      recommendation fields: id, current_priority, suggested_priority, impact_score, confidence, reasoning[].")
	fmt.Println("      explanation.what_if: impact of completing (direct_unblocks, transitive_unblocks, estimated_days_saved).")
	fmt.Println("      explanation.top_reasons: top 3 factors (pagerank, betweenness, blockers, staleness, etc.).")
	fmt.Println("")
	fmt.Println("  Robot Output Filters (bv-84):")
	fmt.Println("      --robot-min-confidence 0.6    Filter by minimum confidence (0.0-1.0)")
	fmt.Println("      --robot-max-results 5         Limit to top N results")
	fmt.Println("      --robot-by-label bug          Filter by label (exact match)")
	fmt.Println("      --robot-by-assignee alice     Filter by assignee (exact match)")
	fmt.Println("")
	fmt.Println("  Label Subgraph Scoping (bv-122):")
	fmt.Println("      --label LABEL                 Scope analysis to label's subgraph")
	fmt.Println("      Affects: --robot-insights, --robot-plan, --robot-priority")
	fmt.Println("      Filters issues to those with the label, then runs analysis on subgraph.")
	fmt.Println("      Includes label_scope and label_context in output with health metrics.")
	fmt.Println("      Example: bt --robot-insights --label api")
	fmt.Println("")
	fmt.Println("  --robot-triage / --robot-next")
	fmt.Println("      Unified triage (mega command) or single top pick. QuickRef includes top picks, quick_wins, blockers_to_clear.")
	fmt.Println("")
	fmt.Println("  --recipe NAME, -r NAME")
	fmt.Println("      Apply a named recipe to filter and sort issues.")
	fmt.Println("      Example: bt --recipe actionable")
	fmt.Println("      Built-in recipes: default, actionable, recent, blocked, high-impact, stale,")
	fmt.Println("                        triage, closed, release-cut, quick-wins, bottlenecks")
	fmt.Println("")
	fmt.Println("  --profile-startup")
	fmt.Println("      Outputs detailed startup timing profile for diagnostics.")
	fmt.Println("      Shows Phase 1 (blocking) and Phase 2 (async) breakdown.")
	fmt.Println("      Provides recommendations based on timing analysis.")
	fmt.Println("      Use with --profile-json for machine-readable output.")
	fmt.Println("")
	fmt.Println("  --workspace CONFIG")
	fmt.Println("      Load issues from workspace configuration file.")
	fmt.Println("      Path: typically .bt/workspace.yaml")
	fmt.Println("      Aggregates issues from multiple repositories with namespaced IDs.")
	fmt.Println("      Example: bt --workspace .bt/workspace.yaml")
	fmt.Println("")
	fmt.Println("  --repo PREFIX")
	fmt.Println("      Filter issues by repository prefix.")
	fmt.Println("      Use with --workspace to focus on one repo in a multi-repo view.")
	fmt.Println("      Matches ID prefixes like 'api-', 'web-', or partial 'api'.")
	fmt.Println("      Example: bt --workspace .bt/workspace.yaml --repo api")
	fmt.Println("")
	fmt.Println("  --source PROJECT[,PROJECT...]")
	fmt.Println("      Scope robot output to one or more source projects (bt-mhwy.6).")
	fmt.Println("      Matches exact ID prefix (e.g. 'bt' in 'bt-mhwy') or the")
	fmt.Println("      SourceRepo field, case-insensitive. Comma-separated for multiple.")
	fmt.Println("      Unknown prefixes yield empty results (not an error).")
	fmt.Println("      Every compact issue record carries a 'source_repo' field")
	fmt.Println("      surfaced by bt-mhwy.1; pair.v1 and portfolio.v1 records key")
	fmt.Println("      on it too.")
	fmt.Println("      Example: bt robot list --source=cass")
	fmt.Println("      Example: bt robot triage --source=bt,cass --global")
	fmt.Println("")
	fmt.Println("  --save-baseline \"description\"")
	fmt.Println("      Save current metrics as a baseline snapshot.")
	fmt.Println("      Stores graph stats, top metrics, and cycle info in .bt/baseline.json.")
	fmt.Println("      Use for drift detection: compare current state to saved baseline.")
	fmt.Println("      Example: bt --save-baseline \"Before major refactor\"")
	fmt.Println("")
	fmt.Println("  --baseline-info")
	fmt.Println("      Show information about the saved baseline.")
	fmt.Println("      Displays: creation date, git commit, graph stats, top metrics.")
	fmt.Println("")
	fmt.Println("  --check-drift")
	fmt.Println("      Check current metrics against saved baseline for drift.")
	fmt.Println("      Exit codes for CI integration:")
	fmt.Println("        0 = No critical or warning alerts (info-only OK)")
	fmt.Println("        1 = Critical alerts (new cycles detected)")
	fmt.Println("        2 = Warning alerts (blocked increase, density growth)")
	fmt.Println("      Human-readable output by default, use --robot-drift for JSON.")
	fmt.Println("")
	fmt.Println("  --robot-drift")
	fmt.Println("      Output drift check as JSON (use with --check-drift).")
	fmt.Println("      Output: {has_drift, exit_code, summary, alerts, baseline}")
	fmt.Println("")
	fmt.Println("  Static Site Export & GitHub Pages (bv-7pu):")
	fmt.Println("      --pages")
	fmt.Println("          Launch interactive Pages deployment wizard.")
	fmt.Println("          Guides you through export -> preview -> deploy to GitHub Pages.")
	fmt.Println("          Handles gh CLI authentication and repository creation.")
	fmt.Println("")
	fmt.Println("      --export-pages <dir>")
	fmt.Println("          Export static HTML site to directory.")
	fmt.Println("          Creates self-contained bundle viewable in any browser.")
	fmt.Println("          Output: index.html, beads.sqlite3, data/*.json, viewer assets")
	fmt.Println("          Example: bt --export-pages ./bv-pages")
	fmt.Println("")
	fmt.Println("      --preview-pages <dir>")
	fmt.Println("          Start local server to preview existing export.")
	fmt.Println("          Opens http://localhost:9000 (or next available port) in your browser.")
	fmt.Println("          Live-reload is enabled by default: browser auto-refreshes on file changes.")
	fmt.Println("          Example: bt --preview-pages ./bv-pages")
	fmt.Println("")
	fmt.Println("      --no-live-reload")
	fmt.Println("          Disable live-reload for --preview-pages (default: live-reload is enabled).")
	fmt.Println("")
	fmt.Println("      --pages-title <title>")
	fmt.Println("          Custom title for the static site (default: 'Project Issues')")
	fmt.Println("")
	fmt.Println("      --pages-include-closed=false")
	fmt.Println("          Exclude closed issues from export (default: include all)")
	fmt.Println("")
	fmt.Println("  Drift Detection Configuration (.bt/drift.yaml)")
	fmt.Println("      Customize drift detection thresholds:")
	fmt.Println("      - density_warning_pct: 50    # Warn if density +50%")
	fmt.Println("      - blocked_increase_threshold: 5   # Warn if 5+ more blocked")
	fmt.Println("      Run 'bt --baseline-info' to see current baseline state.")
	os.Exit(0)
}
